export * from './admin/admin.routes';
export * from './auth/auth.routes';
export * from './balance/balance.routes';
export * from './categoria/categoria.routes';
export * from './etiqueta/etiqueta.routes';
export * from './cuenta/cuenta.routes'
export * from './importacion/importacion.routes';
export * from './moneda/moneda.routes';
export * from './presupuesto/presupuesto.routes'
export * from './recurrente/recurrente.routes';
export * from './regla/regla.routes';
export * from './reporte/reporte.routes';
export * from './transaccion/transaccion.routes';
export * from './transferencia/transferencia.routes';
export * from './usuario/usuario.routes';
export * from './institucion/institucion.routes';
